# version: 2.1

# executors:
#   default_container:
#     docker:
#       - image: circleci/ruby:3.0.1
#         environment:
#           RAILS_ENV: test
#           BUNDLE_JOBS: 4
#           BUNDLE_RETRY: 3
#
#           BUNDLER_VERSION: 2.2.19

#       - image: circleci/mysql:latest
#         command: mysqld --default-authentication-plugin=mysql_native_password
#         environment:
#           MYSQL_ALLOW_EMPTY_PASSWORD: true
#     working_directory: ~/qiita_clone

# commands:
#   install_bundler:
#     description: install bundler
#     steps:
#       - run: gem install bundler -v 2.2.19

# jobs:
#   fetch_source_code:
#     executor:
#       name: default_container
#     steps:
#       - checkout
#       - save_cache:
#           key: v1-qiita_clone-{{ .Environment.CIRCLE_SHA1 }}
#           paths:
#             - ~/qiita_clone

#   bundle_dependencies:
#     executor:
#       name: default_container
#     steps:
#       - restore_cache:
#           key: v1-qiita_clone-{{ .Environment.CIRCLE_SHA1 }}
#       - restore_cache:
#           key: v1-dependencies-{{ checksum "Gemfile.lock" }}

#       - run:
#           name: setup bundler
#           command: |
#             sudo gem uninstall bundler
#             sudo rm /usr/local/bin/bundle
#             sudo rm /usr/local/bin/bundler
#             sudo gem install bundler -v 2.2.19
#       - run:
#           name: Bundle Install Dependencies
#           command: |
#             bundle install
#       - save_cache:
#           key: v1-dependencies-{{ checksum "Gemfile.lock" }}
#           paths:
#             - vendor/bundle

#   rubocop:
#     executor:
#       name: default_container
#     steps:
#       - restore_cache:
#           key: v1-qiita_clone-{{ .Environment.CIRCLE_SHA1 }}
#       - restore_cache:
#           key: v1-dependencies-{{ checksum "Gemfile.lock" }}
#       - install_bundler
#       - run:
#           name: Execute rubocop
#           command: |
#             bundle exec rubocop
#   rspec:
#     executor:
#       name: default_container
#     steps:
#       - restore_cache:
#           key: v1-qiita_clone-{{ .Environment.CIRCLE_SHA1 }}
#       - restore_cache:
#           key: v1-dependencies-{{ checksum "Gemfile.lock" }}

#       - run:
#           name: Watting stand up database
#           command: |
#             dockerize -wait \
#             tcp://127.0.0.1:3306 -timeout 120s
#       # Database setup
#       - run: mv ./config/database.yml.ci ./config/database.yml
#       - install_bundler
#       - run:
#           name: Testing DB migration and seed
#           command: |
#             bundle exec rails db:create db:migrate db:seed db:drop
#       # mkdir directory for upload test results
#       - run: mkdir /tmp/test-results
#       - run: mkdir -p ~/rspec

#       - run:
#           name: Run rspec
#           command: |
#             bundle exec rails db:create db:migrate
#             TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
#             bundle exec rspec --require rails_helper \
#                               --color \
#                               --format progress \
#                               --format RspecJunitFormatter \
#                               --out ~/rspec/rspec.xml
#       # collect reports
#       - store_test_results:
#           path: ~/rspec
#       - store_artifacts:
#           path: ~/tmp/test-results
#           destination: test-results

# workflows:
#   build:
#     jobs:
#       - fetch_source_code
#       - bundle_dependencies:
#           requires:
#             - fetch_source_code
#       - rubocop:
#           requires:
#             - bundle_dependencies
#       - rspec:
#           requires:
#             - bundle_dependencies
version: 2.1

orbs:
  # ruby: circleci/ruby@1.1.2
  ruby: circleci/ruby@1.1.3
  # node: circleci/node@2
  node: circleci/node@4.5.1

# setup
commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

jobs:
  build:
    docker:
      # - image: circleci/ruby:2.7-node
      - image: cimg/ruby:3.0.1-browsers
    steps:
      - setup
  test:
    docker:
      # - image: circleci/ruby:2.7-node
      - image: cimg/ruby:3.0.1-browsers
      # - image: circleci/postgres:11.6-alpine
      - image: circleci/mysql:latest
        name: "db"
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          # POSTGRES_USER: postgres
          # POSTGRES_DB: myapp_test
          # POSTGRES_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    environment:
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
      # PGHOST: 127.0.0.1
      # PGUSER: postgres
      # PGPASSWORD: ""
      RAILS_ENV: test
      BUNDLE_PATH: vendor/bundle
    steps:
      - setup
      - run: mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: rails db:migrate
          command: bundle exec rails db:create db:migrate
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2.1
  test_and_deploy:
  build:
    jobs:
      - build
      - test:
          requires:
            - build
